### ISSUE TITLE
sam_2_fasta returns sequence that is shifted by 1bp when using pysam v0.17

### ISSUE THREAD

**Issue by tnngh** [cov-ert/datafunk#84]
It appears that the string representation of AlignmentSegment in pysam v0.17 now uses 1-based coordinates for the POS field in a sam file.  However, the string representation of AlignmentSegment in pysam v0.16.0.1 (and possibly lower version) used 0-based coordinates for POS field in a sam file.

Accessing the POS field of the sam file using the AlignmentSegment.pos or AlignmentSegment.reference_start API calls always returns 0-based coordinates, whether using pysam v0.16.0.1 or v0.17.

As a result of the change in coordinate system, sequences output by ````datafunk sam_to_fasta```` are right-shifted by 1bp in v0.17.

EG)  For an original sequence  ACGTACGTACGT with trimstart=4, trimend=8

The trimmed and padded sequence output by datafunk sam_2_fasta v0.1.0 with pysam v0.16.0.1 would correctly look like this:

NNNNACGTNNNN

But datafunk sam_2_fasta v0.1.0 with pysam v0.17.0 would incorrectly output this:

NNNNTACGNNNN

**Comment by benjamincjackson** [comment]
@tnguyensanger in the mean time, if it helps, I ported this code into go: https://github.com/cov-ert/gofasta

```
❯ gofasta sam toMultiAlign -h
Convert a SAM file to a multiple alignment in fasta format

Insertions relative to the reference are omitted, so all sequences
in the output are the same ( = reference) length.

Example usage:
	gofasta sam toMultiAlign -s aligned.sam -o aligned.fasta

If you want, you can trim (and optionally pad) the output alignment to coordinates of your choosing:
	gofasta sam toMultiAlign -s aligned.sam --trim --trimstart 250 --trimend 29000 --pad -o aligned.fasta

If input and output files are not specified, the behaviour is to read the sam file from stdin and write
the fasta file to stdout, e.g.:
	minimap2 -a -x asm5 reference.fasta unaligned.fasta | gofasta sam toMultiAlign > aligned.fasta

Usage:
  gofasta sam toMultiAlign [flags]

Aliases:
  toMultiAlign, tomultialign

Flags:
  -o, --fasta-out string   Where to write the alignment (default "stdout")
      --trim               Trim the alignment
      --pad                If trim, replace the trimmed regions with Ns
      --trimstart int      Start coordinate for trimming (0-based, half open) (default -1)
      --trimend int        End coordinate for trimming (0-based, half open) (default -1)
  -h, --help               help for toMultiAlign

Global Flags:
  -r, --reference string   Reference fasta file used to generate the sam file
  -s, --samfile string     samfile to read. If none is specified, will read from stdin
  -t, --threads int        Number of threads to use (default 1)
```

**Comment by benjamincjackson** [comment]
Didn't necessarily mean to have github close this automatically, but the issue should be fixed now. Thank you for the helpful description of the problem!

Ben
